### ISSUE TITLE
[BUG] Weights & Biases logging does not differentiate between modes

### ISSUE THREAD

**Issue by koustuvsinha** [shagunsodhani/ml-logger#25]
Logging using Weights and Biases does not differentiate between training and testing modes in `logbook.write_metric_log({  'mode': 'train' ... })`

**Comment by shagunsodhani** [comment]
@koustuvsinha Thanks for bringing this up. Could you try the new version?

When constructing the logbook, pass an additional parameter:

```
from ml_logger import logbook as ml_logbook
logbook_config = ml_logbook.make_config(
    logger_file_path = <path to write logs>,
    wandb_config = <wandb config or None>,
    wandb_prefix_key = "mode",
)
```
