### ISSUE TITLE
wandb write metric bug

### ISSUE THREAD

**Issue by MohamedAbdelsalam9** [shagunsodhani/ml-logger#75]
I get the following error when I use logbook.write_metric(dict) in the presence of wandb
KeyError: 'One or more of the following keys missing in the metric: step'
This error goes away if using the key "step" in the dictionary dict, but it doesn't serve any purpose.

**Comment by shagunsodhani** [comment]
Thanks for reporting the issue :) `step` key is needed as wandb expects a `step` value when logging metrics. I now see that it is optional though seems useful for [incremental logging](https://docs.wandb.com/library/log#incremental-logging)`. 

The earlier workflow was that you could specify which key to use as `step` when constructing the `logbook_config` using the [`wandb_key_map` argument](https://shagunsodhani.com/ml-logger/ml_logger.html#ml_logger.logbook.make_config). 

Given that the value is optional now, I can set the value to None by default. Do you think that makes sense?

**Comment by shagunsodhani** [comment]
cc @koustuvsinha to get his opinion as well

**Comment by koustuvsinha** [comment]
I advocate for maintaining `step` inside the logger as an object variable - that way, if `step` is not set, then the default value is used (would be useful for tensorboard as well)

**Comment by shagunsodhani** [comment]
I could not find any example where `step` is passed as `None` so I am not passing `None` as the default. `step` key is now optional though. To address @koustuvsinha 's point about tensorboard, since `global_step` can be `None`, we use `None` as the default value.

**Comment by shagunsodhani** [comment]
@MohamedAbdelsalam9 can you reinstall with `pip install "git+https://git@github.com/shagunsodhani/ml-logger.git@0a3edf34c353cfa2209d87ca4b59f976373ac1d0#egg=ml_logger[all]"`

**Comment by shagunsodhani** [comment]
Closing this. Feel free to re-open, if need be.
